#!/usr/bin/env python3
"""Create a BibTeX database containing only entries present in a .bbl file.

The .bbl is used only to obtain citation keys. Full entries are copied
verbatim from the source .bib databases, including fields not printed in the
compiled bibliography (for example DOI, eprint, ADS metadata, and keywords).
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


BIBITEM_RE = re.compile(r"\\bibitem(?:\[[^]]*\])?\{([^}]+)\}")
ENTRY_START_RE = re.compile(r"(?m)^[ \t]*@([A-Za-z]+)\s*([\{(])")
ENTRY_KEY_RE = re.compile(r"^\s*@\w+\s*[\{(]\s*([^,\s]+)\s*,", re.DOTALL)


def bibtex_blocks(text: str, source: Path) -> list[tuple[str, str | None, str]]:
    """Return (type, key, verbatim block) tuples from a BibTeX database."""
    blocks: list[tuple[str, str | None, str]] = []
    position = 0

    while match := ENTRY_START_RE.search(text, position):
        entry_type = match.group(1).lower()
        opener = match.group(2)
        closer = "}" if opener == "{" else ")"
        depth = 1
        in_quotes = False
        escaped = False

        for index in range(match.end(), len(text)):
            character = text[index]
            if escaped:
                escaped = False
                continue
            if character == "\\":
                escaped = True
                continue
            if character == '"':
                in_quotes = not in_quotes
                continue
            if in_quotes:
                continue
            if character == opener:
                depth += 1
            elif character == closer:
                depth -= 1
                if depth == 0:
                    block = text[match.start() : index + 1].strip()
                    key_match = ENTRY_KEY_RE.match(block)
                    key = key_match.group(1) if key_match else None
                    blocks.append((entry_type, key, block))
                    position = index + 1
                    break
        else:
            line = text.count("\n", 0, match.start()) + 1
            raise SystemExit(f"error: unterminated @{entry_type} in {source}:{line}")

    return blocks


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--bbl",
        type=Path,
        default=Path("main.bbl"),
        help="compiled bibliography from which to read citation keys (default: main.bbl)",
    )
    parser.add_argument(
        "--bib",
        type=Path,
        nargs="+",
        default=[Path("main.bib"), Path("aliases.bib")],
        help="source BibTeX databases (default: main.bib aliases.bib)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("cited.bib"),
        help="output BibTeX database (default: cited.bib)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    bbl = args.bbl.resolve()
    sources = [bib.resolve() for bib in args.bib]
    output = args.output.resolve()

    if not bbl.is_file():
        raise SystemExit(f"error: BBL file not found: {bbl}")
    missing = [str(bib) for bib in sources if not bib.is_file()]
    if missing:
        raise SystemExit("error: BibTeX database not found: " + ", ".join(missing))
    if output in sources:
        raise SystemExit("error: output must not overwrite a source BibTeX database")

    keys = BIBITEM_RE.findall(bbl.read_text(encoding="utf-8"))
    keys = list(dict.fromkeys(keys))
    if not keys:
        raise SystemExit(f"error: no \\bibitem keys found in {bbl}")

    directives: list[str] = []
    entries: dict[str, str] = {}
    for source in sources:
        text = source.read_text(encoding="utf-8")
        for entry_type, key, block in bibtex_blocks(text, source):
            if entry_type in {"preamble", "string"}:
                if block not in directives:
                    directives.append(block)
            elif key in keys:
                if key in entries:
                    raise SystemExit(
                        f"error: duplicate cited key {key!r} in the source databases"
                    )
                entries[key] = block

    missing_keys = [key for key in keys if key not in entries]
    if missing_keys:
        raise SystemExit(
            "error: cited keys not found in the source databases: "
            + ", ".join(missing_keys)
        )

    header = (
        "% Generated by extract_cited_bib.py from the citation order in "
        f"{args.bbl}.\n"
        "% Full source entries are preserved verbatim. Manual edits will be\n"
        "% overwritten if this script is run again.\n"
    )
    blocks = directives + [entries[key] for key in keys]
    output_text = header + "\n" + "\n\n".join(blocks) + "\n"

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(output_text, encoding="utf-8")

    print(f"Wrote {len(keys)} entries to {output}")


if __name__ == "__main__":
    main()
